'use strict';
const fullName = 'Zoobia Syyed';
console.log('Value of fullName: ' + fullName);
const isCool = true;
console.log('Value of isCool: ' + isCool);
const totalPets = 1;
console.log('Value of totalPets' + totalPets);
const empty = null;
console.log('value of empty:' + empty);
console.log(typeof empty);
let nothing;
console.log('value of nothing:' + nothing);
console.log(typeof nothing);
