'use strict';
const width = 20;
const height = 47;
const area = width * height;
console.log(area);
console.log(typeof area);
const bill = 300;
const payment = 400;
const change = payment - bill;
console.log(change);
console.log(typeof change);
const quizzes = 5;
const midterm = 3;
const final = 1;
const grade = (quizzes + midterm + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Zoobia';
const lastName = 'Syyed';
const fullName = firstName + ' ' + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 3;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const headCount = 400;
const isSparta = headCount == 300;
console.log(isSparta);
console.log(typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log(motto);
console.log(typeof motto);
